server:
  mem_limit: 4g
  #image: teamcity-server
  build: .
  ports:
   - "8111:8111"
  volumes:
    - .TeamCity:/root/.BuildServer
    #- /home/koby/Incubator/teamcity-coverage-test/coverage-test:/home/koby/coverage-test
agentone:
  privileged: true
  #image: kob-aha/teamcity-agent
  build: teamcity-agent
  volumes:
    - .TeamCity/.buildAgent/1/conf:/opt/buildAgent/conf
  links:
   - server
